services:
  loan:
    image: loan:latest
    container_name: loan_app
    restart: unless-stopped
    build: .
    volumes:
      - ./public:/var/www/html/public
    # ports:
    #   - "9000:9000"
    environment:
      #- APP_DEBUG=true
      - APP_URL=http://localhost:8080
      # SEE README.md FOR MORE INFO
      - APP_KEY=${APP_KEY}
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=loan
      - DB_USERNAME=loan
      - DB_PASSWORD=loan
    depends_on:
      - redis
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
    depends_on:
      - loan

  redis:
    image: redis:8-alpine

  db:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: loan
      MYSQL_USER: loan
      MYSQL_PASSWORD: loan
    volumes:
      - ./data/db:/var/lib/mysql
